# Generated by Django 3.1.4 on 2021-01-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
    ]
