# Generated by Django 3.1.4 on 2021-01-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0002_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recomendador.ocupacion')),
            ],
        ),
    ]
