# Generated by Django 3.1.4 on 2021-01-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_estreno', models.DateField(default=None)),
                ('fecha_estreno_video', models.DateField(default=None)),
                ('imdb_url', models.URLField()),
                ('categorias', models.ManyToManyField(to='recomendador.Genero')),
            ],
        ),
    ]
