# Generated by Django 3.1.4 on 2021-01-18 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0005_auto_20210118_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imdb_url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_puntuacion', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.usuario')),
            ],
        ),
    ]
