# Generated by Django 3.1 on 2021-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0006_auto_20210118_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='fecha_puntuacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
